# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 09:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projectplace', '0002_auto_20180927_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default=datetime.datetime(2018, 9, 30, 9, 10, 9, 533000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
