# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectplace', '0003_post_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published_at',
        ),
    ]
