# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectplace', '0004_remove_post_published_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('film', 'Film'), ('art', 'Art'), ('design', 'Design&Tech'), ('game', 'Games'), ('music', 'Music'), ('other', 'Other')], default='Other', max_length=6),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='Def_img.png', upload_to=None),
        ),
        migrations.AddField(
            model_name='post',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='None', max_length=255, unique=True),
        ),
    ]
