# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-20 08:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectplace', '0006_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConnect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_account', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='Def_img.png', upload_to='img'),
        ),
    ]
